### PR TITLE
test: fix test for components with svg files

### PR DESCRIPTION
**Pull request by justiceotuya**
# Description & Technical Solution

### Describe problems, if any, clearly and concisely.
When an SVG file is imported to a component and that component is tested, we get the error `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` this is because testing SVG was not considered in the template

### Summarize the impact to the system.
After this is merged, testing components with SVG files will run as expected

Please also include relevant motivation and context.
Please include a summary of the technical solution and how it solves the problem.
Added an SVG mock file as stated https://stackoverflow.com/questions/75966690/nextjs-jest-element-type-is-invalid-expected-a-string-for-built-in-component

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] Already rebased against main branch.

# Screenshots
#### Before solution
Screenshot 2023-05-29 at 8 20 58 AM

#### After solution
Screenshot 2023-05-29 at 8 26 22 AM

### CODE REVIEW

**Comment by theodorusclarence** [comment]
Hi! So sorry for the late response, this somehow just got into my attention. 

Due to migration to app directory, SVGR support will be dropped because they have some compatibility issues. We'll see with their updates and will fix them later.

**Comment by theodorusclarence** [comment]
I believe this can be implemented now as of #241, can you update the code?

**Comment by justiceotuya** [comment]
@theodorusclarence code updated

**Comment by theodorusclarence** [comment]
Awesome, thank you @justiceotuya!

**Pull request merged**
